# server
server:
  port: 8081
  servlet:
    context-path: /

# spring
spring:
  #  # 开发阶段使用本地数据库
  #  datasource:
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    driver-class-name: com.mysql.jdbc.Driver
  #    url: jdbc:mysql://192.168.100.207:3306/user?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
  #    username: root
  #    password: root
  # 启动时所使用的配置文件后缀
  profiles:
    active: dev



# Swagger2 doc
swagger2:
  title: 用户权限管理
  name: zoomlgd
  group-name: 用户权限管理服务
  url: http://www.zoomlgd.com/
  email: admin@zoomlgd.com
  description: SpringBoot示例
  license: 州力科技
  license-url: http://www.zoomlgd.com/
  version: 1.0 DEV